In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
import warnings
warnings.filterwarnings('ignore')

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[7, 28]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[24, 18], [7, 28], [19, 22], [13, 22, 5], [16, 11, 13], [21, 18], [1, 11, 22], [26, 29], [26, 10], [9, 24]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[24 18  0  0]
 [ 7 28  0  0]
 [19 22  0  0]
 [13 22  5  0]
 [16 11 13  0]
 [21 18  0  0]
 [ 1 11 22  0]
 [26 29  0  0]
 [26 10  0  0]
 [ 9 24  0  0]]


In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [9]:
model.fit(X, y, epochs=50, verbose=0)

In [10]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.9000 - loss: 0.6200


0.8999999761581421

In [11]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [12]:
weights[13]


array([-0.06853129, -0.11290669,  0.09876169, -0.05277599,  0.02372336],
      dtype=float32)

In [13]:
weights[20]

array([-0.0112417 ,  0.01378432, -0.03158214,  0.01819973, -0.0005518 ],
      dtype=float32)

In [14]:
weights[2]

array([ 0.02122979,  0.02353089,  0.01322291,  0.03415557, -0.03392351],
      dtype=float32)